poll/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'poll.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^poll_demo/', include('poll_demo.urls', namespace="poll_demo")),
    url(r'^admin/', include(admin.site.urls)),
)

poll_demo/urls.py
from django.conf.urls import patterns, url

from poll_demo import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
                           # ex: /poll_demo/5/
    # url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    )

poll_demo/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
        question_text = models.CharField(max_length=200)
        pub_date = models.DateTimeField('date published')

        def __str__(self):
                return self.question_text

        def was_published_recently(self):
            now = timezone.now()
            return now - datetime.timedelta(days=1) <= self.pub_date <= now

        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
        question = models.ForeignKey(Question)
        choice_text = models.CharField(max_length=200)
        votes = models.IntegerField(default=0)

        def __str__(self):
                return self.choice_text

poll_demo/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from poll_demo.models import Question, Choice


# def index(request):
#     latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'poll_demo/index.html', context)
class IndexView(generic.ListView):
    template_name = 'poll_demo/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions(not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'poll_demo/detail.html', {'question': question})
class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll_demo/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'poll_demo/results.html', {'question': question})
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll_demo/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
         # Redisplay the question voting form.
        return render(request, 'poll_demo/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('poll_demo:results', args=(p.id,)))

poll_demo/templates/poll_demo/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'poll_demo:vote' question.id %}" method="post">
    {%  csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
<input type="submit" value="Vote"/>
</form>

poll_demo/templates/poll_demo/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'poll_demo/style.css' %}" />

{%  if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
    <li><a href="{% url 'poll_demo:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available</p>
{% endif %}

poll_demo/templates/poll_demo/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll_demo:detail' question.id %}">Vote again?</a>